# -*- coding: utf-8 -*-
"""ViratKohli_T20_ScorePredictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10BDCnJttqnX5OZHteGJRdFmtEFk6QtGT
"""



"""## Lets Predict Virat Kohli Runs Based on Balls he plays in T20"""

#Problem Solution
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# Load Dataset"""

vk = pd.read_csv("ViratKohli_T20_ScorePredictor - Sheet1.csv")

vk.head()

vk.tail()

vk.shape

"""## Discover and Visualize"""

vk.info()

vk.describe()

plt.scatter(vk['Balls'],vk['Runs'])
plt.xlabel('Balls')
plt.ylabel('Runs')
plt.title('Virat Kohli Scores')
plt.show()

"""## Prepare Data"""

x=vk[['Balls']]
y=vk[['Runs']]
print(x.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=21)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

"""## Select a model and Train It"""

from sklearn.linear_model import LinearRegression
vk_lr=LinearRegression()

vk_lr.fit(x_train,y_train)

c= vk_lr.intercept_[0].round(2)
print(c)

m= vk_lr.coef_[0][0].round(2)
print(m)

print(m*50 + c)

print(vk_lr.predict([[50]])[0][0].round(2))

y_pred = vk_lr.predict(x_test)
y_pred

pd.DataFrame(np.c_[x_test,y_test,y_pred],columns = ["Balls","Runs","Predicted Runs"])

"""## Know Your Prediction Score"""

vk_lr.score(x_test,y_test)

plt.scatter(vk['Balls'],vk['Runs'])
plt.xlabel('Balls')
plt.ylabel('Runs')
plt.title('Virat Kohli Scores')
plt.plot(x_train,vk_lr.predict(x_train), color= "r")
plt.show()

"""## Present Our Solution

**Save ML model**
"""

import joblib
joblib.dump(vk_lr,"score.pkl")

model = joblib.load("score.pkl")

model.predict([[50]])[0][0]

